### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by patrick7166** [ntuee-web-programming/111-1_WebProgramming-Hack2_QA#51]
在routes/info.js的res send 報錯，想請問可能原因

**Comment by ric2k1** [comment]
某個變數自己包自己？

**Comment by patrick7166** [comment]
我一直卡在Part I-3。請問是db find query裡有自己包自己的情況嗎?
console.log (Info.find()回傳的值)裡有
```
Query {
  _mongooseOptions: {},
  _transforms: [],
  _hooks: Kareem { _pres: Map(0) {}, _posts: Map(0) {} },
  _executionStack: null,
  mongooseCollection: Collection {
    collection: Collection { s: [Object] },
    Promise: [Function: Promise],
...
```
TypeError中
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'MongoClient'
    |     property 's' -> object with constructor 'Object'
    |     property 'sessionPool' -> object with constructor 'ServerSessionPool'
    --- property 'client' closes the circle
    at JSON.stringify (<anonymous>)
    ...
    at ServerResponse.send (C:\1_Network\wp1111\hack2\backend\node_modules\express\lib\response.js:162:21)
    at _callee$ (C:\1_Network\wp1111\hack2\backend\src\routes\/info.js:34:25)```
瀏覽器上: AxiosError: Request failed with status code 500\n

**Comment by patrick7166** [comment]
結案，錯在沒有 await instance.get
